In [1]:
import pandas as pd
from pathlib import Path
import mlflow

In [2]:
MLFLOW_DIR = Path("../mlruns").resolve()

mlflow.set_tracking_uri(
    f"file:///{MLFLOW_DIR.as_posix()}"
)

mlflow.set_experiment("AI Text Detection")

print("Tracking URI:", mlflow.get_tracking_uri())

Tracking URI: file:///C:/Users/Drasti/PROG74040-AI-Text-Detection/mlruns

C:\Users\Drasti\anaconda3\envs\aimlcourse\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)

In [3]:
runs = mlflow.search_runs(
    experiment_names=["AI Text Detection"]
)

runs[[
    "tags.mlflow.runName",
    "metrics.test_accuracy",
    "metrics.test_precision",
    "metrics.test_recall",
    "metrics.test_f1",
    "metrics.test_roc_auc"
]]

,tags.mlflow.runName,metrics.test_accuracy,metrics.test_precision,metrics.test_recall,metrics.test_f1,metrics.test_roc_auc
0,RoBERTa,0.998987,0.997653,0.999633,0.998642,0.999951
1,TF-IDF SVM,0.999371,0.999192,0.999118,0.999155,0.999994
2,TF-IDF Logistic Regression,0.994992,0.993312,0.993239,0.993275,0.999743

In [4]:
with mlflow.start_run(run_name="DeBERTa"):

    # Parameters
    mlflow.log_param("model", "microsoft/deberta-base")
    mlflow.log_param("max_length", 256)
    mlflow.log_param("learning_rate", 2e-5)
    mlflow.log_param("train_batch_size", 16)
    mlflow.log_param("epochs", 1)
    mlflow.log_param("training_samples", 100000)
    mlflow.log_param("validation_samples", 20000)
    mlflow.log_param("fp16", False)

    # Original test metrics
    mlflow.log_metric("test_accuracy", 0.996087)
    mlflow.log_metric("test_precision", 0.991243)
    mlflow.log_metric("test_recall", 0.998310)
    mlflow.log_metric("test_f1", 0.994764)
    mlflow.log_metric("test_roc_auc", 0.999901)

    # HC3 external metrics
    mlflow.log_metric("hc3_accuracy", 0.498594)
    mlflow.log_metric("hc3_precision", 0.397516)
    mlflow.log_metric("hc3_recall", 0.999996)
    mlflow.log_metric("hc3_f1", 0.568831)
    mlflow.log_metric("hc3_roc_auc", 0.979550)

print("DeBERTa logged.")

DeBERTa logged.

In [5]:
with mlflow.start_run(
    run_name="TF-IDF Logistic Regression - Final"
):

    mlflow.log_param(
        "model",
        "TF-IDF + Logistic Regression"
    )

    # Original test
    mlflow.log_metric("test_accuracy", 0.994992)
    mlflow.log_metric("test_precision", 0.993312)
    mlflow.log_metric("test_recall", 0.993239)
    mlflow.log_metric("test_f1", 0.993275)
    mlflow.log_metric("test_roc_auc", 0.999743)

    # HC3
    mlflow.log_metric("hc3_accuracy", 0.469753)
    mlflow.log_metric("hc3_precision", 0.378184)
    mlflow.log_metric("hc3_recall", 0.935683)
    mlflow.log_metric("hc3_f1", 0.538655)
    mlflow.log_metric("hc3_roc_auc", 0.758304)

print("Logistic final run logged.")

Logistic final run logged.

In [6]:
with mlflow.start_run(
    run_name="TF-IDF SVM - Final"
):

    mlflow.log_param(
        "model",
        "TF-IDF + LinearSVC"
    )

    # Original test
    mlflow.log_metric("test_accuracy", 0.999371)
    mlflow.log_metric("test_precision", 0.999192)
    mlflow.log_metric("test_recall", 0.999118)
    mlflow.log_metric("test_f1", 0.999155)
    mlflow.log_metric("test_roc_auc", 0.999994)

    # HC3
    mlflow.log_metric("hc3_accuracy", 0.561785)
    mlflow.log_metric("hc3_precision", 0.422031)
    mlflow.log_metric("hc3_recall", 0.878491)
    mlflow.log_metric("hc3_f1", 0.570157)
    mlflow.log_metric("hc3_roc_auc", 0.764126)

print("SVM final run logged.")

SVM final run logged.

In [7]:
runs = mlflow.search_runs(
    experiment_names=["AI Text Detection"]
)

final_view = runs[[
    "tags.mlflow.runName",
    "metrics.test_f1",
    "metrics.hc3_f1",
    "metrics.test_roc_auc",
    "metrics.hc3_roc_auc"
]]

final_view

,tags.mlflow.runName,metrics.test_f1,metrics.hc3_f1,metrics.test_roc_auc,metrics.hc3_roc_auc
0,TF-IDF SVM - Final,0.999155,0.570157,0.999994,0.764126
1,TF-IDF Logistic Regression - Final,0.993275,0.538655,0.999743,0.758304
2,DeBERTa,0.994764,0.568831,0.999901,0.979550
3,RoBERTa,0.998642,NaN,0.999951,NaN
4,TF-IDF SVM,0.999155,NaN,0.999994,NaN
5,TF-IDF Logistic Regression,0.993275,NaN,0.999743,NaN

In [8]:
with mlflow.start_run(
    run_name="RoBERTa - Final"
):

    # Model/training parameters
    mlflow.log_param(
        "model",
        "FacebookAI/roberta-base"
    )

    mlflow.log_param("max_length", 256)
    mlflow.log_param("learning_rate", 2e-5)
    mlflow.log_param("train_batch_size", 16)
    mlflow.log_param("epochs", 2)
    mlflow.log_param("training_samples", 341052)
    mlflow.log_param("fp16", True)

    # Original test metrics
    mlflow.log_metric(
        "test_accuracy",
        0.998987
    )

    mlflow.log_metric(
        "test_precision",
        0.997653
    )

    mlflow.log_metric(
        "test_recall",
        0.999633
    )

    mlflow.log_metric(
        "test_f1",
        0.998642
    )

    mlflow.log_metric(
        "test_roc_auc",
        0.999951
    )

    # HC3 external metrics
    mlflow.log_metric(
        "hc3_accuracy",
        0.490098
    )

    mlflow.log_metric(
        "hc3_precision",
        0.393448
    )

    mlflow.log_metric(
        "hc3_recall",
        0.999352
    )

    mlflow.log_metric(
        "hc3_f1",
        0.564608
    )

    mlflow.log_metric(
        "hc3_roc_auc",
        0.845700
    )

print("RoBERTa final run logged.")

RoBERTa final run logged.

In [9]:
runs = mlflow.search_runs(
    experiment_names=["AI Text Detection"]
)

final_view = runs[[
    "tags.mlflow.runName",
    "metrics.test_f1",
    "metrics.hc3_f1",
    "metrics.test_roc_auc",
    "metrics.hc3_roc_auc"
]]

final_view

,tags.mlflow.runName,metrics.test_f1,metrics.hc3_f1,metrics.test_roc_auc,metrics.hc3_roc_auc
0,RoBERTa - Final,0.998642,0.564608,0.999951,0.845700
1,TF-IDF SVM - Final,0.999155,0.570157,0.999994,0.764126
2,TF-IDF Logistic Regression - Final,0.993275,0.538655,0.999743,0.758304
3,DeBERTa,0.994764,0.568831,0.999901,0.979550
4,RoBERTa,0.998642,NaN,0.999951,NaN
5,TF-IDF SVM,0.999155,NaN,0.999994,NaN
6,TF-IDF Logistic Regression,0.993275,NaN,0.999743,NaN

In [10]:
final_run_names = [
    "TF-IDF Logistic Regression - Final",
    "TF-IDF SVM - Final",
    "RoBERTa - Final",
    "DeBERTa"
]

final_comparison = runs[
    runs["tags.mlflow.runName"].isin(
        final_run_names
    )
][[
    "tags.mlflow.runName",
    "metrics.test_f1",
    "metrics.hc3_f1",
    "metrics.test_roc_auc",
    "metrics.hc3_roc_auc"
]]

final_comparison

,tags.mlflow.runName,metrics.test_f1,metrics.hc3_f1,metrics.test_roc_auc,metrics.hc3_roc_auc
0,RoBERTa - Final,0.998642,0.564608,0.999951,0.845700
1,TF-IDF SVM - Final,0.999155,0.570157,0.999994,0.764126
2,TF-IDF Logistic Regression - Final,0.993275,0.538655,0.999743,0.758304
3,DeBERTa,0.994764,0.568831,0.999901,0.979550